### ISSUE TITLE
outdated tmuxinator version

### ISSUE THREAD

**Issue by lougreenwood** [nexeck/homebrew-tmuxinator#3]
Thanks for this, it's very useful! However, unfortunately, it's now providing quite an outdated version of tmuxinator (0.15), and tmuxinator latest release is now 1.1.1.

The consequences of this is that when using this with latest tmux (2.9), the following warning is shown  when starting tmuxinator:

```
    WARNING: You are running tmuxinator with an unsupported version of tmux.
    Please consider using a supported version:
    (1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8)
```

**Comment by nexeck** [comment]
I have updated tmuxinator to 1.1.1, does this fix the problem for you?

**Comment by lougreenwood** [comment]
Yep, fixes, thanks!!! 🙏
